### ISSUE TITLE
How To Self-Host?

### ISSUE THREAD

**Issue by karimawi** [pinodex/spotify-now-playing-overlay#28]
Hey, first of all, your overlay is very nifty and makes the stream cool

I noticed you have a 60-minute expiration time for the tokens, and I have to regenerate the link 2 or 3 times during the stream and I don't even notice it sometimes, I know removing the time limit would be catastrophic for the API application, so could you please help me set this up with my own Spotify dev app and deploy it from my machine and completely remove the token thing.

**Comment by NeonLightning** [comment]
this
